config/routes.rb
Rails.application.routes.draw do
  get '/login', to:'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout'      , to: 'sessions#destroy'
  root to: "events#index"
  
  resources :users, only: [:new, :create, :show]
  resources :events, only: [:new, :create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  include SessionsHelper
end

app/models/attendance_event.rb
class AttendanceEvent < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendance_events, foreign_key: :attended_event_id
  belongs_to :creator, class_name: 'User'
  has_many :attendees, through: :attendance_events

  scope :past, -> { where("date < date('now')") }
  scope :upcoming, -> { where("date > date('now')") }

  validates :creator_id, presence: true
  validates :tittle, presence: true
  validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendance_events, foreign_key: :attendee_id

  has_many :attended_events, through: :attendance_events

  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event'

  has_secure_password

  def upcoming_events
    attended_events.where('date > date(\'now\')')
  end

  def previous_events
    attended_events.where('date < date(\'now\')')
  end

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include UsersHelper
  include EventsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(events_params)
    if @event.save
      flash[:message] = 'New event created'
      redirect_to event_path(@event)

    else
      flash.now[:message] = 'Something went wrong'
      render 'new'
    end
  end

  def show
    @event = Event.find_by(id: params[:id])
    @event.attendees 
  end

  def index
    @created_events = Event.all
    @past_events = Event.past
    @upcoming = Event.upcoming
  end

  def events_params
    params.require(:event).permit(:tittle, :description, :date, :location)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(id: params[:session][:user_id])
    if @user
      login(@user.id)
      redirect_to user_path(@user.id)
    else
      flash.now[:message] = 'Incorrect'
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
      login(@user.id)
      @user.attended_event_ids.clear
    else
      render 'new'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @attended_event = Event.all
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
    def addatendees(x)
        @event.atendees = @x
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user_id)
    session[:user_id] = user_id
  end

  def current_user
    @user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    session.delete(:user_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def attend?(upcoming_event, attended_events)
    x = false
    attended_events.each do |y|
      x = true if y.id == upcoming_event.id
    end
    !x
  end
end

app/views/events/index.html.erb
<div class="event-header">
  <h1 style="text-align:center;">Browse all events</h1>
 <% if logged_in? %>
  <%= link_to 'Create Event', new_event_path, class: 'btn btn-primary btn-lg pull-right' %>
<% end %>
</div>

<div class="container" style="text-align:center;">

<h2>Upcoming Events</h2>

<div class="grid size" style=" display: inline-grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  padding: 10px;
  grid-gap: 1em;">
<% Event.upcoming.all.each do |event_upcoming| %>

<div style="border:solid; border-radius:1rem;" class="grid-item">
  <a href="<%= event_path(event_upcoming) %>">  
  <h3> <%= event_upcoming.tittle %>  <%= event_upcoming.date.to_date %>  </h3>
  </a> 
  <p> Creator : <span style="font-size: 20px; color:red;"> <%= event_upcoming.creator.name %> </span> </p>
  <p> <%= event_upcoming.description %> </p>
  </div>
<% end %> 
</div>
<h2>Previous Events</h2>

<div class="grid size" style=" display: inline-grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  padding: 10px;
  grid-gap: 1em;">
<% Event.past.all.each do |event_past| %>
<div style="border:solid; border-radius:1rem;" class="grid-item">
<a href="<%= event_path(event_past) %>">  
  <h3 class=""> <%= event_past.tittle %>  <%= event_past.date.to_date %>  </h3>
</a>
  <p> Creator : <span style="font-size: 20px; color:red; "> <%= event_past.creator.name %> </span> </p>
  <p> <%= event_past.description %> </p>
</div>
<% end %>
</div >
</div>

app/views/events/new.html.erb
<h1>Create a new Event</h1>
<% if flash[:message] %>
  <%= @event.errors.full_messages %>
<% end %>
<%= form_for @event do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Name of the event' %>
    <%= f.text_field :tittle , class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :location, 'Location' %>
    <%= f.text_field :location, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :date, 'Date' %>
    <%= f.date_field :date, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, 'Describe your event' %>
    <%= f.text_area :description, class:'form-control' %>
  </div>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/events/show.html.erb
<%= flash[:message] %>

<h1> <%= @event.tittle %> </h1>
<h3> Location: <%= @event.location %> </h3>
<h3> Date: <%= @event.date.to_date %> </h3>
<p> <%= @event.description %> </p>
<h2> Attendees: </h2>

<%= form_for @event do |f| %>
<f.select multiple="multiple" size="User.all.length" id="user_names"
name="user_names[]">
<% User.all.each do |user| %>
  <option value="<%= user.name %>">
    <%= user.name %>
  </option>
<% end %>
</select>

  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/_header.html.erb
<header id="main-header" class="navbar navbar-inverse">
<div class="container d-flex align-items-center">
  <nav class="row" >
            <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                    <li> <%= link_to "Events", events_path %></li>
                    <li> <%= link_to current_user.name, user_path(current_user) %>  </li>
                    <li> <%= link_to "Logout", logout_path, method: 'DELETE' %></li>
                <% else %>
                    <li><%= link_to "Login", login_path %></li>
                    <li><%= link_to "Sign Up", new_user_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user do |f|%>
    <%= f.label :name, 'Name'%>
    <%= f.text_field :name, class:'form-control' %>
    <%= f.label :email, 'Email'%>
    <%= f.text_field :email, class:'form-control' %>
    <%= f.label :password, 'Password' %>
    <%= f.password_field :password, class:'form-control' %>
    <%= f.label :password_confirmation, 'Password confirmation' %>
    <%= f.password_field :password_confirmation, class:'form-control' %>
    <%= f.submit "Submit", class:'btn btn-primary' %>
  <% end %> 

app/views/users/show.html.erb
<h3><%= @user.name %></h3>
<h4><%= @user.email %></h4>


<h2> Created events </h2>

<div class="grid size" style=" display: inline-grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  padding: 10px;
  grid-gap: 1em;">
<% @user.created_events.each do |event| %>
<div style="border:solid; border-radius:1rem; text-align:center;" class="grid-item">
<p>  
  <h3> <%= event.tittle %> <p style="font-size: 15px; "> <br><span style="color:black;">Date :</span><%= event.date.to_date %> </p> </h3>
  <p style="border-top:solid;"> <%= event.description %> </p>
</p>
</div>
<% end %>
</div>

<h2> Attended events </h2>

<div class="grid size" style=" display: inline-grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  padding: 10px;
  grid-gap: 1em;
  text-align:center;">
<% @user.attended_events.each do |attend_event| %>
<div style="border:solid; border-radius:1rem;" class="grid-item">
  <span style = "font-size:20px; color:grey;"><%= attend_event.date%><br></span>
  <p style="color:black;border-top:solid;">
<%= attend_event.tittle %></p>
</div>
<% end %>
</div>


<h2> Upcoming events </h2>

<div class="grid size" style=" display: inline-grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  padding: 10px;
  grid-gap: 1em;
  text-align:center;">
<% Event.upcoming.each do |upcoming_event| %>
<div style="border:solid; border-radius:1rem;" class="grid-item">
  <span style="color:blue;">
  <h3 ><%= upcoming_event.tittle %>
  <%= upcoming_event.date.to_date %>
  <%if attend?(upcoming_event,@user.attended_events.all)%>
  <button style="border:2; border-radius: 10px;">
  <a href="<%= event_path(upcoming_event) %>"> attend this event </a>
  </button>
  <%else%>
  <button class="btn-info" >
  <a href="<%= event_path(upcoming_event) %>" style="color:white;"> already attended </a>
  </button>
  <%end%>
  
  </button>
  </h3>
  </span>
  
</a>
</div>
<% end %>
</div>

<h2> Previous events </h2>

<div class="grid size" style=" display: inline-grid;
  grid-template-columns: 1fr 1fr 1fr 1fr;
  padding: 10px;
  grid-gap: 1em;
  text-align:center;">
<% Event.past.each do |previous_event| %>
<div style="border:solid; border-radius:1rem;" class="grid-item">
  <a href="<%= event_path(previous_event) %>">    
  <h3><%= previous_event.tittle %>
  <%= previous_event.date.to_date %></a></h3>
</a>
</div>
<% end %> 
</div>